/**
 * ID2-02: SAML 2.0 adapter contract + stub
 * @task ID2-02
 * @frd FR-CORE-ID-001
 *
 * defines the saml adapter interface for enterprise idp integration.
 * phase 2 delivers oidc; saml is contract-only with a stub implementation
 * that returns SamlNotConfigured. the interface matches the oidc claim
 * mapping pattern from ID2-01 for consistent identity handling.
 */

import { Result } from '@aptivo/types';
import type {
  SamlAdapter,
  SamlError,
  SamlLoginResult,
  SamlMetadata,
} from '@aptivo/types';

// re-export for convenience
export type { SamlAdapter, SamlError, SamlLoginResult, SamlMetadata };

// -- stub implementation --

/**
 * creates a stub saml adapter that returns SamlNotConfigured for all operations.
 * used when saml is not configured (phase 2 default).
 *
 * supabase saml capability assessment:
 * - saml 2.0 support requires supabase pro plan ($25/mo per project)
 * - supported idps: okta, azure ad, google workspace, onelogin, auth0
 * - configuration via supabase dashboard → authentication → sso
 * - sp-initiated login only (no idp-initiated)
 * - assertion consumer service (acs) url auto-generated by supabase
 *
 * @see docs/04-specs/authentication.md §6.4 for integration plan
 */
export function createSamlStubAdapter(): SamlAdapter {
  const notConfigured: SamlError = {
    _tag: 'SamlNotConfigured',
    message: 'SAML is not configured. Enable Supabase Pro plan and configure SSO providers.',
  };

  return {
    async initiateLogin(_domain: string) {
      return Result.err(notConfigured);
    },

    async handleCallback(_samlResponse: string) {
      return Result.err(notConfigured);
    },

    getMetadata() {
      return Result.err(notConfigured);
    },
  };
}

// -- saml claim mapping bridge --

/**
 * maps a saml assertion's attributes to the same MappedIdentity shape
 * used by the oidc claim mapper, enabling uniform downstream handling.
 */
export interface SamlClaimMapperDeps {
  /** saml attribute name that contains group memberships */
  groupAttribute: string;
  /** mapping from idp group name → aptivo role */
  groupToRoleMapping: Record<string, string>;
  /** default role when no groups map */
  defaultRole: string;
}

export interface SamlMappedIdentity {
  externalId: string;
  email: string;
  name: string;
  roles: string[];
  providerId: string;
}

export function createSamlClaimMapper(deps: SamlClaimMapperDeps) {
  return {
    mapAssertion(
      assertion: { nameId: string; attributes: Record<string, string | string[]> },
      providerId: string,
    ): Result<SamlMappedIdentity, SamlError> {
      const groupsRaw = assertion.attributes[deps.groupAttribute];
      const groups = Array.isArray(groupsRaw) ? groupsRaw : groupsRaw ? [groupsRaw] : [];

      const mappedRoles = groups
        .map((g) => deps.groupToRoleMapping[g])
        .filter((r): r is string => r !== undefined);

      const roles = mappedRoles.length > 0 ? mappedRoles : [deps.defaultRole];
      const uniqueRoles = [...new Set(roles)];

      const email = assertion.nameId;
      // handle attributes that may be string or string[]
      const displayName = assertion.attributes['displayName'];
      const cn = assertion.attributes['cn'];
      const resolvedDisplayName = Array.isArray(displayName) ? displayName[0] : displayName;
      const resolvedCn = Array.isArray(cn) ? cn[0] : cn;
      const name = resolvedDisplayName ?? resolvedCn ?? email;

      return Result.ok({
        externalId: assertion.nameId,
        email,
        name,
        roles: uniqueRoles,
        providerId,
      });
    },
  };
}
